#!/data/data/com.termux/files/usr/bin/bash

echo ""
echo "  1) Audio only"
echo "  2) Whole Playlist"
echo "  3) 240p Video  press 3"
echo "  4) 360p Video  press 4"
echo "  5) 480p Video  press 5"
echo "  6) 720  Video  press 6"
echo "  7) 1080p Video press 7"
echo "  8) 2k Video    press 8"
echo "  9) 4k Video    press 9"
echo "Choose an option:"

myorder='--no-warnings --newline -no-mtime -o /data/data/com.termux/files/home/storage/shared/Download/%(uploader)s/%(playlist)s/%(playlist_index)s/%(title)s.%(ext)s -f'
command='--no-warnings --newline -no-mtime -o /data/data/com.termux/files/home/storage/shared/Download/%(title)s.%(ext)s -f'
title=$(youtube-dl --get-title $1)

read option
echo -e "Download Started"

case $option in
1 )
echo "$command 140" > ~/.config/youtube-dl/config
youtube-dl $1
;;
2 )
echo "$myorder best" > ~/.config/youtube-dl/config
youtube-dl $1
;;
3 )
echo "$command \"best[height<=240]\"" > ~/.config/youtube-dl/config
youtube-dl $1
;;
4 )
echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config
youtube-dl $1
;;
5 )
echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config
youtube-dl $1
;;
6 )
echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config
youtube-dl $1
;;
7 )
echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config
youtube-dl $1
;;
8 )
echo "$command \"best[height<=1440]\"" > ~/.config/youtube-dl/config
youtube-dl $1
;;
9 )
echo "$command \"best[height<=2160]\"" > ~/.config/youtube-dl/config
youtube-dl $1
;;
* )
echo -e "Finding Best Quality of Your Video"
echo "$command best" > ~/.config/youtube-dl/config # " -f best " > best video+audio
youtube-dl $1
;;
esac
